notifications:
  email:
    if: branch = master

branches:
  only:
  - master
  - develop

os :
  - linux

dist:
  - xenial

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - "pip install pybullet"
  - "pip install numpy --upgrade"
  - "pip install codecov"
  - "python setup.py develop --agree-license"

script:
  - cd tests
  - coverage run test_launcher.py

after_success:
  - codecov